version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  # Including this due to certain github action steps installing via npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
